In [1]:
import pandas as pd

/opt/anaconda3/lib/python3.12/site-packages/pandas/core/computation/expressions.py:22: UserWarning: Pandas requires version '2.10.2' or newer of 'numexpr' (version '2.8.7' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED
/opt/anaconda3/lib/python3.12/site-packages/pandas/core/arrays/masked.py:56: UserWarning: Pandas requires version '1.4.2' or newer of 'bottleneck' (version '1.3.7' currently installed).
  from pandas.core import (

In [22]:
df = pd.read_excel('Personal Finance.xlsx',sheet_name ='January')
df.head(10)

,OUTFLOW EVERYMONTH,EXPENSES,INCOME,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
0,425,RENT,7231.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,42.15,WIFI & RECHARGE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0,ELECTRICITY BILL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,152,OPAL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,127,GROCIERS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,0,WOOLIES,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,107,SWIMMING,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,25,beer and pizza,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,50,withdraw,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,56,food,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
jan =df [['OUTFLOW EVERYMONTH','EXPENSES ']]
jan.head()

  OUTFLOW EVERYMONTH          EXPENSES
0                425               RENT
1              42.15    WIFI & RECHARGE
2                  0  ELECTRICITY BILL
3                152               OPAL
4                127           GROCIERS

In [4]:
jan = jan.rename(columns ={'OUTFLOW EVERYMONTH' :'Amount',"EXPENSES " : 'Category'})

In [6]:
jan['Amount'] = pd.to_numeric(jan['Amount'], errors ='coerce')

In [7]:
jan = jan.dropna()

In [8]:
jan = jan.drop([10,11,12])

In [122]:
df = pd.read_excel('Personal Finance.xlsx',sheet_name =None)
month = ['Novemeber ','December ','January','feb','March','april']
all_months =[]
for sheet_name,df1 in df.items():
    if sheet_name in month:
        df_month =df1
        df_month =df1 [['OUTFLOW EVERYMONTH','EXPENSES ']]
        df_month =df_month.rename(columns ={'OUTFLOW EVERYMONTH' :'Amount',"EXPENSES " : 'Category'})
        df_month['Amount'] = pd.to_numeric(df_month['Amount'], errors ='coerce')
        df_month = df_month.dropna()
        df_month = df_month[~df_month['Category'].isin(["TOTAL","MANDATORY ","UNWANTED "])]
        df_month["months"] = sheet_name
        all_months.append(df_month)
combined_months = pd.concat(all_months,ignore_index = True)
print(combined_months)

    Amount                 Category      months
0   425.00                     RENT   December
1    42.15                    WIFI    December
2    44.90                 recharge   December
3   174.36                     OPAL   December
4   105.10                     BEER   December
5    14.85                 GROCIERS   December
6    28.85                  WOOLIES   December
7   160.68                 SWIMMING   December
8   102.09               FOOD/movie   December
9   104.00                     trip   December
10  425.00                     RENT       april
11   48.95          WIFI & RECHARGE       april
12   34.00        ELECTRICITY BILL        april
13   20.00                     OPAL       april
14   70.39                 GROCIERS       april
15   18.80                  WOOLIES       april
16  168.00             acceesorries       april
17  300.00                    aunty       april
18   26.00                     food       april
19  425.00                     RENT       March
20   48.95          WIFI & RECHARGE       March
21    0.00        ELECTRICITY BILL        March
22  213.74                     OPAL       March
23   49.13                 GROCIERS       March
24   12.75                  WOOLIES       March
25   35.00             acceesorries       March
26  491.89                    india       March
27  103.00                     food       March
28  425.00                     RENT         feb
29   42.15          WIFI & RECHARGE         feb
30  153.75        ELECTRICITY BILL          feb
31  191.25                     OPAL         feb
32   87.31                 GROCIERS         feb
33   34.00                  WOOLIES         feb
34    0.00           beer and pizza         feb
35   41.50                     food         feb
36  425.00                     RENT     January
37   42.15          WIFI & RECHARGE     January
38    0.00        ELECTRICITY BILL      January
39  152.00                     OPAL     January
40  127.00                 GROCIERS     January
41    0.00                  WOOLIES     January
42  107.00                 SWIMMING     January
43   25.00           beer and pizza     January
44   50.00                 withdraw     January
45   56.00                     food     January
46  425.00                     RENT  Novemeber
47   62.05          WIFI & RECHARGE  Novemeber
48  185.50        ELECTRICITY BILL   Novemeber
49  162.00                     OPAL  Novemeber
50  108.35                     BEER  Novemeber
51   85.34                 GROCIERS  Novemeber
52   46.24                  WOOLIES  Novemeber
53  140.12                 SWIMMING  Novemeber
54  116.01  HEALTHCARE VACCINATION   Novemeber
55   86.49                     FOOD  Novemeber